pipeline {
    agent any

    stages {
        stage('Test') {
            environment {
                SONAR_TOKEN = credentials('SONAR_TOKEN')
                SONAR_HOST_URL = credentials('SONAR_HOST_URL')
                PROJECT_KEY = credentials('PROJECT_KEY')
            } 
            agent {
                docker { 
                    image 'sonarsource/sonar-scanner-cli:latest'
                    args '-u root'
                    reuseNode true  
                }
              }
            steps {
                script {
                    sh """
                        sonar-scanner \
                            -Dsonar.projectKey=${PROJECT_KEY} \
                            -Dsonar.sources=. \
                            -Dsonar.host.url=${SONAR_HOST_URL} \
                            -Dsonar.login=${SONAR_TOKEN}
                    """
                }
            }

            post {
                always {
                    sh 'docker rmi sonarsource/sonar-scanner-cli:latest || true'
                }
            }            
        }

        stage('Build') {
            environment {
                DOCKER_IMAGE = credentials('docker-image')
                DOCKERHUB_CREDENTIALS = credentials('dockerhub-cred')
            }            
            agent {
                docker { 
                    image 'docker:dind'
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u root:root'
                    reuseNode true
                }
            }
            
            steps {
                script {
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                    def customImage = docker.build("${DOCKER_IMAGE}")
                    customImage.push()
                    customImage.push("${DOCKER_TAG}")
                    sh 'docker logout'
                }
            }
            
            post {
                always {
                    sh 'docker rmi docker:dind || true'
                }
            }
        }

        stage ('Deploy') {
            environment {
                HOST_IP = credentials('host-ip')
            }        
            agent { 
                docker { 
                    image 'ubuntu:22.04'
                    reuseNode true 
                }  
            } 
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'remote-server-cred', keyFileVariable: 'SSH_PRIVATE_KEY', usernameVariable: 'REMOTE_USER')]) {
                    sh """
                    apt update && apt install openssh-client -y
                    ssh -o StrictHostKeyChecking=no -i ${SSH_PRIVATE_KEY} ${REMOTE_USER}@${HOST_IP} '
                    docker pull gerrome/react-site
                    docker run -p 5000:80 -d gerrome/react-site 
                    '
                    """
                }
            }
            post {
                always {
                    sh 'docker rmi ubuntu:22.04 || true'
                }
            }                 
        }
    }

    post {
        always {
            cleanWs()
            sh 'docker system prune -af || true'
        }
    }
}